/*
 * @Author: Leo l024983409@qq.com
 * @Date: 2023-10-15 19:32:39
 * @LastEditors: Leo l024983409@qq.com
 * @LastEditTime: 2023-10-21 20:27:34
 * @FilePath: \cms\src\shared\enums\env.enum.ts
 * @Description:
 */
export enum EnvEnum {
	APP_ENV = "APP_ENV",
	APP_PORT = "APP_PORT",

	DATABASE_URL = "DATABASE_URL",

	JWT_PUBLIC_KEY = "JWT_PUBLIC_KEY",
	JWT_PRIVATE_KEY = "JWT_PRIVATE_KEY",
	JWT_ACCESS_TOKEN_EXPIRES_IN = "JWT_ACCESS_TOKEN_EXPIRES_IN",
	JWT_REFRESH_TOKEN_EXPIRES_IN = "JWT_REFRESH_TOKEN_EXPIRES_IN",

	LOG_LEVEL = "LOG_LEVEL",
	TIMESTAMP = "TIMESTAMP",
	LOG_ON = "LOG_ON",

	REDIS_PORT = "REDIS_PORT",
	REDIS_HOST = "REDIS_HOST",
	REDIS_PASSWORD = "REDIS_PASSWORD",

	UPLOAD_ADDRESS = "UPLOAD_ADDRESS",
}
